const PHRASES = [
  "kočka",
  "domeček",
  "jablko",
  "rodina",
  "bota",
  "auto",
  "motorka",
  "brýle",
  "zahrada",
  "pampeliška",
  "motýlek",
  "papoušek",
  "kamarád",
  "písmeno",
  "knihovna",
  "pohádka",
  "třešně",
  "jahoda",
  "višně",
  "banán",
  "sklenice",
  "čokoláda",
  "kytara",
  "písnička",
  "králík",
  "želva",
  "andulka",
  "sněhulák",
  "zvířátko",
  "barevný",
  "barva",
  "malování",
  "sluníčko",
  "hvězdička",
  "měsíček",
  "pískoviště",
  "houpačka",
  "klouzačka",
  "koloběžka",
  "tramvaj",
  "vlakové",
  "nádraží",
  "vafle",
  "dortík",
  "chleba",
  "máslo",
  "polévka",
  "snídaně",
  "svačina",
  "večeře",
  "kamínek",
  "větev",
  "stromek",
  "kapr",
  "pstruh",
  "žirafa",
  "tygr",
  "slonice",
  "krokodýl",
  "ježek",
  "ježibaba",
  "kouzelnice",
  "čaroděj",
  "perníček",
  "sněženka",
  "sedmikráska",
  "pradědeček",
  "babička",
  "dědeček",
  "maminka",
  "tatínek",
  "Petr",
  "Lucie",
  "Tereza",
  "Matyáš",
  "Adéla",
  "Kristýna",
  "Tomáš",
  "Barbora",
  "Dominik",
  "Matouš",
  "Mikuláš",
  "Štěpán",
  "Daniela",
  "Zuzana",
  "Vilém",
  "Hynek",
  "Praha",
  "Brno",
  "Ostrava",
  "Olomouc",
  "Zlín",
  "Plzeň",
  "Tábor",
  "Třebíč",
  "Český Krumlov",
  "Jihlava",
  "Hradec Králové",
  "Jája pije z hrnku.",
"Pája čumí na sovu.",
"Sova čučí v lese.",
"Srnka čůrá na louce.",
"Divočák kadí u lesa.",
"Jelen jásá na louce.",
"Máma pije vodu.",
"Táta má pilu.",
"Táta řeže dřevo pilou.",
"Tomík pípá jako pták.",
"Sova létá nad stromkem.",
"Kočka pije mléko.",
"Králík pase trávu.",
"Želva leze pomalu.",
"Ježek se tulí.",
"Andulka pípá v kleci.",
"Papoušek čučí na děti.",
"Motýlek létá nad lípou.",
"Sluníčko svítí v létě.",
"Hvězdička bliká na nebi.",
"Dítě lepí papír.",
"Malá pusa se směje.",
"Maminka vaří polévku.",
"Tatínek maže chleba máslem.",
"Dáme si sladký dortík.",
"Vafle jsou moc dobré.",
"Jahoda voní v misce.",
"Banán leží na stole.",
"Sklenice je plná vody.",
"Čokoláda se rozpouští.",
"Kamarád má barevnou kytaru.",
"Děti zpívají písničku.",
"Čteme pohádku v domečku.",
"Knihovna má hodně knížek.",
"Písmeno skáče na papíře.",
"Dítě maluje barvy.",
"Pampeliška roste na louce.",
"Sedmikráska se usmívá.",
"Sněženka kouká ze sněhu.",
"Stromek má zelené listy.",
"Ježibaba vaří lektvar.",
"Kouzelnice čaruje hůlkou.",
"Čaroděj má klobouk.",
"Perníček voní sladce.",
"Sněhulák stojí na zahradě.",
"Zvířátko pije z misky.",
"Tygr řve v pohádce.",
"Slonice má dlouhý chobot.",
"Žirafa kouká z výšky.",
"Krokodýl čučí z vody.",
"Děti skáčou na houpačce.",
"Klouzačka klouže dolů.",
"Koloběžka jede rychle.",
"Tramvaj cinká.",
"Vlakové nádraží je velké.",
"Auto stojí u domu.",
"Motorka brumlá.",
"Bota leží pod stolem.",
"Rodina se směje.",
"Kočka spí v domečku.",
];

window.PHRASES = PHRASES;
