window.STICKERS = [
  {
    id: "sticker-01",
    name: "Statečný čtenář",
    image: "assets/sticker-01.png",
    threshold: 5,
  },
  {
    id: "sticker-02",
    name: "Mistr kostek",
    image: "assets/sticker-02.png",
    threshold: 10,
  },
  {
    id: "sticker-03",
    name: "Atomový génius",
    image: "assets/sticker-03.png",
    threshold: 20,
  },
  {
    id: "sticker-04",
    name: "Kočka stavitel",
    image: "assets/sticker-04.png",
    threshold: 30,
  },
  {
    id: "sticker-05",
    name: "Kostičkový hrdina",
    image: "assets/sticker-05.png",
    threshold: 40,
  },
  {
    id: "sticker-06",
    name: "Jaderný dozorce",
    image: "assets/sticker-06.png",
    threshold: 50,
  },
  {
    id: "sticker-07",
    name: "Hazmat parťák",
    image: "assets/sticker-07.png",
    threshold: 60,
  },
  {
    id: "sticker-08",
    name: "Lego věžák",
    image: "assets/sticker-08.png",
    threshold: 70,
  },
  {
    id: "sticker-09",
    name: "Pixelový kočičák",
    image: "assets/sticker-09.png",
    threshold: 80,
  },
  {
    id: "sticker-10",
    name: "Reaktorový strážce",
    image: "assets/sticker-10.png",
    threshold: 90,
  },
  {
    id: "sticker-11",
    name: "Kostkový mág",
    image: "assets/sticker-11.png",
    threshold: 100,
  },
  {
    id: "sticker-12",
    name: "Kočka a reaktor",
    image: "assets/sticker-12.png",
    threshold: 110,
  },
  {
    id: "sticker-13",
    name: "Lego robot",
    image: "assets/sticker-13.png",
    threshold: 120,
  },
  {
    id: "sticker-14",
    name: "Hazmat průzkumník",
    image: "assets/sticker-14.png",
    threshold: 130,
  },
  {
    id: "sticker-15",
    name: "Pixelový diamant",
    image: "assets/sticker-15.png",
    threshold: 140,
  },
  {
    id: "sticker-16",
    name: "Kočičí reaktor",
    image: "assets/sticker-16.png",
    threshold: 150,
  },
  {
    id: "sticker-17",
    name: "Kostičkový drak",
    image: "assets/sticker-17.png",
    threshold: 160,
  },
  {
    id: "sticker-18",
    name: "Atomová radost",
    image: "assets/sticker-18.png",
    threshold: 170,
  },
];
